# Generated by Django 5.0.1 on 2024-02-17 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('text_content', models.TextField(blank=True)),
                ('drone', models.CharField(blank=True, max_length=100)),
                ('private', models.BooleanField(blank=True, default=False)),
                ('favourite', models.BooleanField(blank=True, default=False)),
            ],
        ),
    ]
