# Generated by Django 5.0.1 on 2024-02-17 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gallery', '0001_initial'),
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='image',
            field=models.ManyToManyField(related_name='galleries', to='image.image'),
        ),
    ]
