# Generated by Django 5.0.1 on 2024-02-17 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('question', models.CharField(max_length=100)),
                ('text_description', models.TextField()),
                ('likes_count', models.PositiveIntegerField(default=0)),
                ('dislike_count', models.IntegerField(default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now_add=True)),
                ('reply_count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
